version: '3'
services:
  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    volumes: 
      - ./tmp/db:/var/lib/postgresql/data
    networks:
      - my-network
    environment: 
      POSTGRES_USER: "runner"
      POSTGRES_PASSWORD: "runner-password"
  web:
    build: .
    links:
      - "db:db"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    networks: 
     - my-network
      
networks: 
 my-network: 
   driver: bridge
